## Powerlevel10k Configuration
POWERLEVEL9K_DISABLE_RPROMPT="true"
#POWERLEVEL9K_PROMPT_ON_NEWLINE="true"
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_debian_icon dir vcs)
POWERLEVEL9K_CUSTOM_DEBIAN_ICON="echo "
#POWERLEVEL9K_CUSTOM_DEBIAN_ICON_BACKGROUND="227"
#POWERLEVEL9K_DIR_HOME_BACKGROUND="56"
#POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="56"
