#! /bin/sh

sxhkd &
dunst &
compton &
$HOME/.config/lemonbar/lemonbar.sh &
setxkbmap -layout fr &
wal  -i /home/scupake/Pictures/lunala.jpeg &
xset -b & #For annoying beeping sounds

#workspace
bspc monitor -d 1 2 3 4 5

#Border gaps,width, and padding
bspc config border_width         0
bspc config window_gap           8
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 
bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
 
#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
