#! /bin/sh

#### AUTOSTART ####
xsetroot -cursor_name left_ptr &
~/.fehbg &
budgie-panel &
play .Login &
sxhkd -m 1 &
compton &
synclient TapButton1=1 TapButton2=3 TapButton3=2 & #For laptop touchpad
xset -b & #For annoying beeping sounds
volumeicon &
nm-applet &
pulseaudio &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 & 

#### WORKSPACES AND BORDERS ####

#Monitor allocation and their workspaces
bspc monitor -d 1 2 3 4 5

#Border gaps,width, and padding
bspc config border_width         2.5
bspc config window_gap           20
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

#Focus on pointer
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config normal_border_color         "#000000"
bspc config focused_border_color        "#f7f8f8"
bspc config active_border_color         "#f7f8f8"
